@startuml

[*] --> Запрос
Запрос -down-> Получение
Получение -down-> Упаковка
Получение -down-> Получение
Упаковка -right-> Отправка
Отправка -right-> Отправлено
Отправлено -up-> Запрос
Отправлено -down-> [*]

@enduml
