@startuml
class ВУЗ {
	Название
	Адрес
	Телефон
	--
	добавитьСтудента();
	отчислитьСтудента();
	списокСтудентов();
}

class Факультет {
	Название
	--
	добавитьПреподавателя();
	списокПреподавателей();
}

class Преподаватель {
	Имя
	--
	узнатьИмя();
	вестиЛекцию();
}

class Курс {
	Название
	Идентификатор
}

class Студент {
	Имя
	Идентификатор
}

ВУЗ "1" o-right- "   1..n" Факультет : Состоит из >
Студент -down-o "1..n" ВУЗ : Обучается в >
Студент "0..n" -right- "0..n" Курс : Посещает >
Преподаватель "1..n" -left- "0..n" Курс : Читает <
Факультет "0..1" -- "\n\nдекан\n0..1" Преподаватель
Факультет "1..n" o-- "1..n" Преподаватель : Работает\n <
@enduml
