@startuml
|#AntiqueWhite|Пользователь|
|Программа|
start

|Программа|
:Запрос первого числа>
|Пользователь|
:Число<
|Программа|
:Запрос второго числа>
|Пользователь|
:Число<
|Программа|
:Вычисление]
:Результат>

stop
@enduml
