@startuml
|Программа|
|#AntiqueWhite|Пользователь|
|Программа|
start

|Программа|
:Запрос первого числа>
|Пользователь|
:Число<
|Программа|
:Запрос знака>
|Пользователь|
:Символ<
|Программа|
if (знак == /) then (yes)
(A)
detach
(A)
  |Программа|
  repeat
	|Программа|
    :Запрос второго числа>
    |Пользователь|
    :Число<
  |Программа|
  repeat while (Второе число == 0) is (yes)
else (no)
  |Программа|
  :Запрос второго числа>
  |Пользователь|
  :Число<
endif
|Программа|
:Вычисление]
:Результат>

stop
@enduml
