@startuml
|#AntiqueWhite|Пользователь|
|Программа|
start

|Программа|
:Запрос первого числа>
|Пользователь|
:Число<
|Программа|
:Запрос знака>
|Пользователь|
:Символ<
|Программа|
:Запрос второго числа>
|Пользователь|
:Число<
(A)
detach
(A)
|Программа|
if (знак == / И второе число != 0) then (yes)
  :Выбор действия;
  :Вычисление]
  :Результат>
else (no)
  :Некорректный ввод>
endif

stop
@enduml
