@startuml

start
:Числа А и Б<
:Указатели на\nкоэффициенты А и Б<

while (А != Б) is (да)

  if (А > Б) then (да)
    :А = А - Б]
    :множительА ++]
  else (нет)
    :Б = Б - А]
    :множительБ ++]
  endif
endwhile (нет)

:Расчёт коэффициентов\nА и Б по формуле\n(коэффА = (1 / множА) / 2)\nи запись по указателям]
:Число А>
stop
@enduml
