@startuml

start
:Числа А и Б\nУказатели на коэффициенты для А и Б<

if (Б == 0) then (да)
  :КоэффА = 1, КоэффБ = 0;
  :Число А>
  stop
endif
while (Б > 0) is (да)
	:ВП1 = А / Б]
	note left: на основе этой\nвременной переменной\nбудут считаться коэффициенты
	:ВП2 = А - ВП1 * Б]
	note left: на основе этой\nвременной переменной\nбудет считаться НОД
	:КоэффА = х2 - ВП1 * х1, КоэффБ = у2 - ВП1 * у1;
	:А = Б, Б = ВП2\nх2 = х1, х1 = х, у2 = у1, у1 = у;
endwhile (нет)

:КоэффА = х2, КоэффБ = у2]
:Число А>
stop
@enduml
