@startuml

start
:Проверяеемое число А;
:Количество проверяемых чисел = 255;

while (А < 255) is (да)
  :Проверить среди найденных простых чисел\nне делится ли А на одно из них без остатка|
  if (Не поделилось без остатка) then (да)
    :Число простое, добавить в\nсписок к другим простым числам;
  endif
  :А++]
endwhile (нет)
:Список простых чисел>
stop
@enduml
