@startuml

start
:Число А<
:Число Б<

while (А != Б) is (да)

'  if (a > b) then (да)
'    :a = a - b]
'  else (нет)
'    :b = b - a]
'  endif

endwhile (нет)

:Число А>
note left: На этом этапе А и Б\nравны и являются НОД\nпервоначальных чисел

stop
@enduml


/'
int gcd(int a, int b) {
   int t;
   while (b) {
     t = a % b;
     a = b;
     b = t;        
   }
   return a;
}
'/
