@startuml

start
:Число А<
:Число Б<

while (Б != 0) is (да)
	:Т = Остатку от деления А на Б]
	:А = Б]
	:Б = Т]
endwhile (нет)

:Число А>
note left: На предыдущем шаге\nБ поделилось без остатка на А,\nзначит являлось НОД А и Б

stop
@enduml
