@startuml
start

:Исходное число<
:Сумма цифр равна нулю;
while (исходное число больше нуля?) is (да)
	:Прибавить к сумме крайнюю правую цифру исходного числа]
	:Отбросить от исходного числа крайнюю правую цифру]
endwhile (нет)
:Сумма цифр>
stop
@enduml
