@startuml
start
    :Число до которого будет считаться число Факториал<
    
    if (Передаваемое число равно нулю?) then (да)
        :Вернуть единицу>
        stop
    else (Нет)
        :Рекурсивно вычислить значение числа Факториал;
        :Перемножить текущее значения с рекурсивно расчитанным;
        :Вернуть результат>
    endif
stop
@enduml