@startuml
start
    :Число до которого будет считаться число Фибоначчи<
    
    if (Передаваемое число равно нулю) then (да)
        :Вернуть ноль>
        stop
    else (Нет)
        if (Передаваемое число равно единице) then (да)
            :Вернуть единицу>
            stop
        else (Нет)
            :Рекурсивно вычислить значение первого члена последовательности;
            :Рекурсивно вычислить значение второго члена последовательности;
            :Сложить результаты полученные для двух членов последовательности;
            :Вернуть результат;
        endif
    endif
stop
@enduml