@startuml
start
    :Число до которого будет считаться число Фибоначчи<
    
    if (Передаваемое число равно нулю) then (да)
        :Вернуть единицу>
        stop
    else (Нет)
        :Рекурсивно вычислить значение числа Фибоначчи;
        :Перемножить текущее значения с рекурсивно расчитанным;
        :Вернуть результат;
    endif
stop
@enduml