@startuml

start
:Число для которого нужно посчитать факториал<
:Результат равен нулю;
if (Число больше нуля?) then (да)
	:Результат равен произведению текущего числа на <b>Факториал(Числа - 1)</b> ;
elseif (Число равно нулю) then (да)
	:Результат равен 1;
endif
:Результат>
stop
@enduml
