@startuml
start
    :Число до которого будет считаться число Фибоначчи<
    
    if (Передаваемое число равно нулю?) then (да)
        : Ноль >
    elseif (Передаваемое число равно единице?) then (да)
        : Единица >
    else (Нет)
        : <b> Фибоначчи(Число - 1)</b> + <b> Фибоначчи(Число - 2)</b> >
    endif
stop
@enduml
