@startuml
start
    :Число на основе которого будет вычисляться треугольное<
    :;
    
    if (Передаваемое число равно единице) then (Да)
        :Вернуть единицу>
        stop
    else (Нет)
        :Рекурсивно вычислить значение треугольного числа;
        :Прибавить к текущему значению результат рекурсивного расчёта;
        :Сложить результаты всех рекурсивных вычислений;
        :Вернуть результат>
    endif
stop
@enduml