@startuml
start
:Порядковый номер треугольного числа<
if (Номер больше одного?) then (да)
	:Результат равен сумме текущего номера и <b>ТреугольноеЧисло(Номер - 1)</b> ;
elseif (Номер равен единице) then (да)
	:Результат равен 1;
endif
:Результат>
stop
@enduml
