@startuml
start
    :Передать массив<
    :Передать размер массива<
    :Передать размер для которого будет проводится поиск<
    
    if (Размер поиска равен единице?) then (Да)
        :Завершить рекурсивный вызов;
        stop
    else (Нет)
        while (Достигнуто ли значение поиска?) is (Нет)
            :Рекурсивно вызвать функцию поиска анаграмм;

            if (Значение поиска стало равно двум?) then (Да)
            :Вызвать функцию отображения массива;
            endif
            
            :Вызвать функцию перестановки символов в массиве;
        endwhile (Да)
    endif
stop
@enduml