@startuml
start
    :С какого стержня переложить<
    :На какой стержень переложить<
    :Количество перекладываемых колец<
    
    :Определить промежуточный стержень перекладки;

    if (Количество перекладываемых колец равно единице?) then (Да)
        :Переложить с одного кольца на другое;
    else (Нет)
        :Рекурсивно вызвать функцию с указанием промежуточного кольца в качестве конечного;
        :Переложить с одного кольца на другое;
        :Рекурсивно вызвать функцию с указанием промежуточного кольца в качестве начального;
    endif
stop
@enduml