@startuml
start
    :Передаём номер ферзя<


    if (Есть ли на доске свободное место?) then (Нет)
        :0>
        stop
    endif
    
    if (Возможно ли разместить на доске ещё одного ферзя?) then (Нет)
        :1>
        stop
    endif
    
    while (Превышено ли значение по вертикали?) is (Нет)
        while (Превышено ли значение по горизонтали?) is (Нет)
            if (Свободна ли ячейка доски?) then (Да)
                :Присвоить клетке номер ферзя;
                if (Возможно ли рекурсивно установить ещё одного ферзя?) then (Да)
                    :1>
                    stop
                endif
                :Освободить клетку доски;
            endif
        endwhile (Да)
        :0>
        stop
    endwhile (Да)
stop
@enduml