@startuml
start
    :Передаём положение коня по оси X<
    :Передаём положение коня по оси Y<
    :Передаём количество сделанных ходов<

    :Определяем для клетки доски номер хода;

    if (Превышает ли количество шагов максимально допустимое?) then (Да)
        :1>
        stop
    endif

    while (Есть ли возможность разместить ещё одного коня?) is (Да)
        :Определяем следующую позицию по оси X;
        :Определяем следующую позицию по оси Y;
        if (Возможно ли рекурсивно сделать следующий ход?) then (Нет)
            :1>
            stop
        endif
    endwhile (Нет)
    
    :Освободить клетку доски;
    :0>
stop
@enduml