@startuml
start
    :Передаём координату X<
    :Передаём координату Y<

    if (X и Y равны нулю?) then (Да)
        :0>
        stop
    else (Нет)
        if (X или Y равны нулю?) then (Да)
            :1>
            stop
        else (Нет)
            :Рекурсивно решаем задачу маршрута меняя координату Y;
            :Рекурсивно решаем задачу маршрута меняя координату X;
            :Суммируем количество расчитанных маршрутов;
            :Возвращаем значение суммы маршрутов>
        endif
    endif
stop
@enduml