@startuml
start
    :Передаём строковый литерал A<
    :Передаём строковый литерал B<

    if (Литерал A или литерал B равен символу конца строки?) then (Да)
        :0>
        stop
    else (Нет)
        if (Равен ли литерал A литералу B?) then (Да)
            :Вызвать функцию рекурсивно;
            :Вернуть сумму единицы и результат рекурсивного подсчёта>
            stop
        endif
    endif
        :Решаем задачу подпоследовательности для литерала A;
        :Решаем задачу подпоследовательности для литерала B;
        :Выбираем максимальную из полученных длин;
        :Возвращаем значение максимальной длины>
stop
@enduml