@startuml
start
    :Обрабатываемый массив<

    while (Конец массива?) is (Нет)
        :Прибавить значение к общей сумме;
        :Взять следующий элемент массива;
    endwhile
    
    : Среднее арифметическое >
stop
@enduml