@startuml
start
    :Искомое число<

    while (Конец массива?) is (Нет)
        while (Текущий элемент равен искомому числу) is (Да)
            :Текущий индекс>
            stop
        endwhile (Нет)
        :Взять следующий элемент массива;
    endwhile (Да)
    
    : -1 >
stop
@enduml