@startuml
start
    :Обрабатываемое множество<

    while (Конец множества?) is (Нет)
        :Прибавить значение к общей сумме;
        :Взять следующий элемент множества;
    endwhile (Да)
    
    :Разделить сумму на общее количество элементов;
    :Среднее арифметическое >
stop
@enduml