@startuml
start
    :Обрабатываемый массив<
    :Номер первой колонки<
    :Номер второй колнки<

    while (Конец массива?) is (Нет)
        :Временной переменной присвоить значение из второй колонки;
        :Значению второй колонки присвоить значение из первой колонки;
        :Значению первой колонки присвоить значение из временной переменной;
		:Переместиться к следующей строке;
    endwhile (Да)

stop
@enduml
