@startuml
start
    :Обрабатываемый массив<
    :Первая колонка<
    :Вторая колнка<

    while (Конец массива?) is (Нет)
        :Временной переменной присвоить значение второй колонки;
        :Значению второй колонки присвоить значение первой колонки;
        :Значению первой колонки присвоить значение временной переменной;
    endwhile (Да)

stop
@enduml