@startuml
start
:Массив и длина массива Н <

while (Н-ный проход по массиву?) is (Нет)
  while (Конец массива?) is (Нет)
    if (Значение по текущему индексу больше, чем по следующему?) then (Да)
      : Поменять местами;           
    else (Нет)
    endif
	:Следующий индекс;
  endwhile (Да)
(a)
detach
(a)
  while (Начало массива?) is (Нет)
    if (Значение по текущему индексу меньше, чем по предыдущему?) then (Да)
      : Поменять местами;           
    else (Нет)
    endif
	:Предыдущий индекс;
  endwhile (Да)

  : Следующий проход по массиву;
endwhile (Да)

stop
@enduml
