@startuml
start
:Массив и длина массива Н <

while (Н-ный проход по массиву?) is (Нет)
  while (Конец массива?) is (Нет)
    if (Значение по текущему индексу больше, чем по следующему?) then (Да)
      : Поменять местами;           
    else (Нет)
    endif
	:Следующий индекс;
  endwhile (Да)
  : Следующий проход по массиву;
endwhile (Да)

stop
@enduml
