@startuml
start
: Массив и длина массива Н  < 
while (Конец массива?) is (Нет)
   : Текущее значение отметить флажком;
    while (Конец оставшегося массива?) is (Нет)
	if (Текущий элемент меньше найденного минимального?) then (Да)
   : Обозначить найденное значение как минимальное;
   endif
   :Следующий элемент;
    endwhile (Да)
: Поменять местами найденный элемент и отмеченный флажком;   
endwhile (Да)
stop
@enduml
