@startuml
start
: Массив и длина массива Н  < 
while (Н-ный проход по массиву?) is (Нет)
   :Положить сортируемый элемент во временную переменную; 
   while (Сортируемый элемент меньше крайнего\nэлемента отсортированной части массива?) is (Да)
     :Сдвинуть крайний элемент отсортированной\nчасти массива на свободное место;
   endwhile (Нет)
	 : Вставить сортируемый элемент на свободное место;   
endwhile (Да)
stop
@enduml
