@startuml
start
: Массив <
: Искомое значение<
  while (Конец массива или искомое найдено?) is (Нет)
    :Следующий индекс;
  endwhile (Да)
  if (Достигли конца массива?) then (Да)
    : -1 >        
  else (Нет)
  	: Индекс >
  endif

stop
@enduml
