@startuml
start
: Массив <
: Искомое значение<
: Поместить искомое в конец массива\nкак дополнительный элемент;
  while (Конец массива?) is (Нет)
    :Следующий индекс;
  endwhile (Да)
  : Индекс >

stop
@enduml
