@startuml
start
: Массив <
: Искомое значение<
  while (Левая граница меньше или равна правой?) is (Да)
    :Вычислить проверяемый элемент по формуле\nЛ + ((искомое - массив[Л]) * (Р - Л)) / (массив[Р] - массив[Л]);
	if (Проверяемый элемент == искомому?) then (Да)
	   : Индекс проверяемого элемента >
	else if (Проверяемый элемент меньше искомого?) then (Да)
	   : Сдвинуть левую границу проверяемого массива;
	else (Нет)
	   : Сдвинуть правую границу проверяемого массива;
	endif
  endwhile (Нет)
  : -1 >

stop
@enduml
