@startuml
start
    :Массив<
    :Максимальное значение в массиве<
    :Создать массив счётчиков;
    :Обнулить массив счётчиков;

    while (Конец начального массива?) is (Нет)
            :Увеличить на единицу значение по индексу массива счётчиков, равному\nзначению элемента начального массива;
    endwhile (Да)
    
    while (Конец массива счётчиков?) is (Нет)
        while (Значение в ячейке равно нулю?) is (Нет)
			:Записать в исходный массив значение равное индексу массива счётчиков;
			:Увеличить индекс для записи в исходном массиве;
        endwhile (Да)
    endwhile (Да)
stop
@enduml
