@startuml
start
    :Передаём массив для сортировки values<
    :Передаём максимальное значение содержащееся в массиве max_value<

    :Создаём массив счётчиков counts[0 to max_value];
    
    while (Конец массива счётчиков counts?) is (Нет)
        :Присвоить элементу массива counts нулевое значение;
    endwhile (Да)

    while (Конец массива счётчиков counts?) is (Нет)
        :Увеличить значение счётчика на единицу если найдено похожее значение в массиве;
    endwhile (Да)
    
    while (Достигнуто максимальное значение max_value?) is (Нет)
        while (Конец массива счётчиков counts?) is (Нет)
            :Копируем в массив values значение текущей итерации, от нуля до max_value,
            количество раз указанно для текущего значения в массиве счётчиков counts;
        endwhile (Да)
    endwhile (Да)
stop
@enduml