@startuml
start
    :Массив<
    :Найти минимальное и максимальное значение в массиве;
	:Найти диапазон значений (разницу между минимумом и максимумом);
    :Создать массив счётчиков размером с диапазон значений начального массива;
    :Обнулить массив счётчиков;

    while (Конец начального массива?) is (Нет)
            :Увеличить на единицу значение по индексу массива счётчиков, равному\nзначению элемента начального массива;
    endwhile (Да)
(A)
detach
(A)
    while (Конец массива счётчиков?) is (Нет)
        while (Значение в ячейке равно нулю?) is (Нет)
			:Записать в исходный массив значение равное индексу массива счётчиков,\nувеличенное на значение минимума исходного массива;
			:Увеличить индекс для записи в исходном массиве;
        endwhile (Да)
    endwhile (Да)

stop
@enduml
