@startuml
start
    :Передаём массив для сортировки arr<

    :Находим минимальное значение массива min;
    :Находим минимальное значение массива max;
    :Находим количество элементов лежащих между минимальным и максимальным значениями массив - spread;
    :Определим размер вспомогательного массива supportArr как (spread + 1);
    
    while (Конец вспомогательного массива supportArr?) is (Нет)
        :Присвоить элементу массива supportArr нулевое значение;
    endwhile (Да)

    while (Конец массива arr?) is (Нет)
        :Увеличать значение счётчика на единицу если найдено похожее значение в массиве;
    endwhile (Да)
    
    while (Конец массива supportArr?) is (Нет)
        while (Значение вспомогательного массива supportArr больше нуля?) is (Да)
            :Присвоить элементу исходного массива arr значение столько раз сколько оно входит во вспомогательный массив;
            :Увеличить значение счётчика count указывающего на индекс элемента исходного массива arr;
            :Уменьшить значение счётчика для элемента вспомогательного массива supportArr на единицу;
        endwhile (Нет)
    endwhile (Да)
stop
@enduml