@startuml
start
    :Передать массив для сортировки array<
    :Передать глубину заполнения каждой корзины size<

    :Присвоить значение максимальной глубины константе max;
    :Определить константу количества корзин buckets;
    :Определяем переменные требуемые для обхода массива корзин bucket;
    :Обойти все корзины в цикле и присвоить каждому конечному элементу корзин значение 0;
    :Определить переменную digit;

    while (digit меньше или равно size?) is (Да)
        while (Достигнуто значение max?) is (Нет)
            :Непонятная конструкция;
        endwhile (Да)
        :Определить переменную idx;
        while (Достигнуто максимальное значение корзин buckets?) is ()
            while (Достигнут ли конец массива bucket) is (Нет)
                :Присвоить исходному массиву array значение из очередной корзины bucket;
            endwhile (Да)
            :Присвоить конечному элементу очередной корзины значение 0;
        endwhile (Да)
    endwhile (Нет)

stop
@enduml