@startuml
start
    :Массив и его размер <

    :Максимальная глубина корзин = размер массива;
    :Определить константу количества корзин\n(обычно остаток от деления на степени 10);
    :Очистить корзины;

    while (Перебрали все разряды значений массива?) is (Нет)
        while (Конец массива?) is (Нет)
            :Положить значение в корзину, соответвтующую полученному разряду;
        endwhile (Да)
(A)
detach
(A)
		while (Перебрали все корзины?) is (Нет)
            while (Перебрали все элементы внутри корзины?) is (Нет)
                :Присвоить исходному массиву текущее значение из текущей корзины;
            endwhile (Да)
			:Очистить счётчик внутри текущей корзины;
        endwhile (Да)
    endwhile (Да)

stop
@enduml
