@startuml
start
    :Массив и его размер <

    while (Рассматриваем единственный элемент?) is (Нет)
		:Разделить массив пополам;
		
    	while (Последний элемент части массива?) is (Нет)
			if (Текущий элемент больше\nсоответствующего элемента\nотстоящего на размер\nтекущей части массива?) then (Да)
			   :Поменять элементы местами;
			endif
		
    	endwhile (Да)

	endwhile (Да)

stop
@enduml
